// US state -> primary IANA timezone, for converting a prospect's local time to Alaska time.
// A few states span multiple zones (e.g. TX, FL, MI, KY, ID, OR, ND, SD, KS, NE, IN, AZ) —
// mapped to their most populous zone, which is fine for a "close enough" phone-sales tool.
export const US_STATE_TIMEZONES: { code: string; name: string; tz: string }[] = [
  { code: 'AL', name: 'Alabama', tz: 'America/Chicago' },
  { code: 'AK', name: 'Alaska', tz: 'America/Anchorage' },
  { code: 'AZ', name: 'Arizona', tz: 'America/Phoenix' },
  { code: 'AR', name: 'Arkansas', tz: 'America/Chicago' },
  { code: 'CA', name: 'California', tz: 'America/Los_Angeles' },
  { code: 'CO', name: 'Colorado', tz: 'America/Denver' },
  { code: 'CT', name: 'Connecticut', tz: 'America/New_York' },
  { code: 'DE', name: 'Delaware', tz: 'America/New_York' },
  { code: 'DC', name: 'District of Columbia', tz: 'America/New_York' },
  { code: 'FL', name: 'Florida', tz: 'America/New_York' },
  { code: 'GA', name: 'Georgia', tz: 'America/New_York' },
  { code: 'HI', name: 'Hawaii', tz: 'Pacific/Honolulu' },
  { code: 'ID', name: 'Idaho', tz: 'America/Denver' },
  { code: 'IL', name: 'Illinois', tz: 'America/Chicago' },
  { code: 'IN', name: 'Indiana', tz: 'America/New_York' },
  { code: 'IA', name: 'Iowa', tz: 'America/Chicago' },
  { code: 'KS', name: 'Kansas', tz: 'America/Chicago' },
  { code: 'KY', name: 'Kentucky', tz: 'America/New_York' },
  { code: 'LA', name: 'Louisiana', tz: 'America/Chicago' },
  { code: 'ME', name: 'Maine', tz: 'America/New_York' },
  { code: 'MD', name: 'Maryland', tz: 'America/New_York' },
  { code: 'MA', name: 'Massachusetts', tz: 'America/New_York' },
  { code: 'MI', name: 'Michigan', tz: 'America/New_York' },
  { code: 'MN', name: 'Minnesota', tz: 'America/Chicago' },
  { code: 'MS', name: 'Mississippi', tz: 'America/Chicago' },
  { code: 'MO', name: 'Missouri', tz: 'America/Chicago' },
  { code: 'MT', name: 'Montana', tz: 'America/Denver' },
  { code: 'NE', name: 'Nebraska', tz: 'America/Chicago' },
  { code: 'NV', name: 'Nevada', tz: 'America/Los_Angeles' },
  { code: 'NH', name: 'New Hampshire', tz: 'America/New_York' },
  { code: 'NJ', name: 'New Jersey', tz: 'America/New_York' },
  { code: 'NM', name: 'New Mexico', tz: 'America/Denver' },
  { code: 'NY', name: 'New York', tz: 'America/New_York' },
  { code: 'NC', name: 'North Carolina', tz: 'America/New_York' },
  { code: 'ND', name: 'North Dakota', tz: 'America/Chicago' },
  { code: 'OH', name: 'Ohio', tz: 'America/New_York' },
  { code: 'OK', name: 'Oklahoma', tz: 'America/Chicago' },
  { code: 'OR', name: 'Oregon', tz: 'America/Los_Angeles' },
  { code: 'PA', name: 'Pennsylvania', tz: 'America/New_York' },
  { code: 'RI', name: 'Rhode Island', tz: 'America/New_York' },
  { code: 'SC', name: 'South Carolina', tz: 'America/New_York' },
  { code: 'SD', name: 'South Dakota', tz: 'America/Chicago' },
  { code: 'TN', name: 'Tennessee', tz: 'America/Chicago' },
  { code: 'TX', name: 'Texas', tz: 'America/Chicago' },
  { code: 'UT', name: 'Utah', tz: 'America/Denver' },
  { code: 'VT', name: 'Vermont', tz: 'America/New_York' },
  { code: 'VA', name: 'Virginia', tz: 'America/New_York' },
  { code: 'WA', name: 'Washington', tz: 'America/Los_Angeles' },
  { code: 'WV', name: 'West Virginia', tz: 'America/New_York' },
  { code: 'WI', name: 'Wisconsin', tz: 'America/Chicago' },
  { code: 'WY', name: 'Wyoming', tz: 'America/Denver' },
]
